### PR TITLE
Add bintray repo

### PR DESCRIPTION
**Pull request by auroredea**
Add bintray publish support in the build of the project.
You are able to add version in your own project.
 Resolve issue scalacenter/scaladex#444

### CODE REVIEW

**Comment by MasseGuillaume** [comment]
Merci!

**Comment by laughedelic** [comment]
It's kinda ironic that a library for working with semantic versions doesn't follow semantic versioning itself 😆  `0.1.?`

**Comment by MasseGuillaume** [comment]
@laughedelic 

Maybe I should rename SemanticVersion to Version. It supports a bit more than SemanticVersion.
https://github.com/scalacenter/versions/blob/master/src/test/scala/ch.epfl.scala.version/SemanticVersionTests.scala#L34. It was designed to support most of the version schemes I saw on the Scala ecosystem.

We could also have a strict one that implements the specs properly.

**Comment by laughedelic** [comment]
Sounds good to me. The repo is already called `versions`. 

I wanted to use it for parsing semantic versions (in sbt), but then I couldn't resolve the artifact for Scala 2.12 and wrote a quick hack with a regex 😅 

It's great that @auroredea took the initiative and published the library, but I think that it should be published in the https://bintray.com/scalacenter org and preferably in a repo linked to JCenter. Also it would be nice to have it for both Scala 2.11 and 2.12.

**Comment by MasseGuillaume** [comment]
@laughedelic I will release on maven central. @auroredea released it on Bintray since it was part of a Scala Spree and we only had a short amount of time to make it work.

**Comment by laughedelic** [comment]
I see. Nice 👍

**Comment by MasseGuillaume** [comment]
@laughedelic it's now available on maven central

```
libraryDependencies += "ch.epfl.scala" %% "versions" % "0.1.0"
```

`ch.epfl.scala.version.SemanticVersion` follows the specs.

**Comment by laughedelic** [comment]
@MasseGuillaume Great! 👍

**Pull request merged**
